### PR TITLE
Object browser redesign with new block slot usage

### PR DESCRIPTION
**Pull request by juwara0**
#MAJOR#

Closes: https://github.com/ciena-frost/ember-frost-object-browser/issues/32 https://github.com/ciena-frost/ember-frost-object-browser/issues/42 https://github.com/ciena-frost/ember-frost-object-browser/issues/43 https://github.com/ciena-frost/ember-frost-object-browser/issues/44 https://github.com/ciena-frost/ember-frost-object-browser/issues/49

# CHANGELOG

## Breaking

* **Redesigned** block-slot usage for all slots
* **Updated** README to explain the new slots and the usage for each slot
* **Updated** integration and unit tests to cover the new object-browser functionality

---
This change is [Reviewable](https://reviewable.io/reviews/ciena-frost/ember-frost-object-browser/48)

### CODE REVIEW

**Comment by rox163** [comment]
:+1:

**Comment by rox163** [comment]
:+1:

**Comment by rox163** [comment]
:+1:

**Comment by sglanzer** [comment]
Closing in favor of the PR that retains the prior behavior alongside the new slots behavior

**Pull request closed without merging**
