### PR TITLE
Fixes https://github.com/ciena-frost/ember-frost-object-browser/issues/117

### PR DESCRIPTION
**Pull request by EWhite613**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* Fixes https://github.com/ciena-frost/ember-frost-object-browser/issues/117
  * Fix misaligned action bar buttons on Firefox

### CODE REVIEW

**Comment by EWhite613** [comment]
# Without fix
**Button has unaccounted for extra margin**
without-fix
# With fix
**The unaccounted for margin is removed**
with-fix

Is this okay @baconC @pbosse ?

**Comment by PoplarToppler** [comment]
You have tested in firefox, right?

**Comment by EWhite613** [comment]
@PoplarToppler ya, the frost-action-bar-buttons looks the same as the one in chrome now

**Comment by sglanzer** [comment]
I think the better option may be to just remove the whitespace - try this
```
{{#each controls as |control|}}
    {{~ component control ~}}
  {{/each}}
```
Here https://github.com/ciena-frost/ember-frost-object-browser/blob/master/addon/templates/components/frost-action-bar.hbs

**Comment by sglanzer** [comment]
See `Whitespace Control` here http://handlebarsjs.com/expressions.html

**Comment by sglanzer** [comment]
Approved

**Comment by sglanzer** [comment]
Didn't realize this was also fixing misalignment - I'm good with the current solution

**Comment by sglanzer** [comment]
Approved

**Pull request merged**
