### PR TITLE
update version ember-frost-core

### PR DESCRIPTION
**Pull request by EWhite613**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* Use latest minor for `ember-frost-core`

### CODE REVIEW

**Comment by juwara0** [comment]
The blueprint will need to be updated as well.

**Comment by juwara0** [comment]
This will need to be a server major since you are moving the version of core up a major.

**Comment by EWhite613** [comment]
Dependent on https://github.com/ciena-frost/ember-frost-list/pull/156 which is dependent on ciena-frost/ember-frost-sort#69

**Comment by EWhite613** [comment]
Dependent on https://github.com/ciena-frost/ember-frost-list/pull/156 which is dependent on ciena-frost/ember-frost-sort#69

**Pull request closed without merging**
