### PR TITLE
BPSO-73463 fix css for hidden moreAction components

### PR DESCRIPTION
**Pull request by gkchestertron**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* improved css to handle hidden items in the moreActions popover

### CODE REVIEW

**Comment by gkchestertron** [comment]
image

**Comment by gkchestertron** [comment]
Old
image

**Comment by notmessenger** [comment]
👍

**Comment by gkchestertron** [comment]
Thanks, @notmessenger - I think this is the last one.

**Comment by cstolli** [comment]
"more" button looks great!

**Pull request merged**
